name: Build

on:
  push:
    branches: 
    - master

  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  build-solution:
    name: Build solution
    uses: CCSWE-nanoframework/actions-nanoframework/.github/workflows/build-solution.yml@master
    secrets: inherit
    with:
      solution: 'CCSWE.nanoFramework.DhcpServer.sln'